version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"  # Expose React app on port 80
    depends_on:
      - server  # Make sure the server starts before the client

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"  # Expose Node.js server on port 5000
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app  # Mount the server directory for live changes
    restart: always
